### ISSUE TITLE
Use of source code

### ISSUE THREAD

**Issue by TheCommCraft** [programORdie2/scratchrequest#1]
You should add a notice to the license from github.com/TheCommCraft/scratchcommunication because you used part of the source code.

**Comment by RetrogradeDev** [comment]
Uhm, what?

**Comment by TheCommCraft** [comment]
It just looks like you used a modified version of https://github.com/TheCommCraft/scratchcommunication/blob/main/scratchcommunication/cloud.py

**Comment by TheCommCraft** [comment]
Still not resolved...

**Comment by RetrogradeDev** [comment]
https://scratch.mit.edu/projects/877978019/#comments-351170928 ...

**Comment by TheCommCraft** [comment]
You didn't change anything

programORdie2 ***@***.***> schrieb am Fr., 25. Aug. 2023,
21:47:

**Comment by RetrogradeDev** [comment]
I have already credited you in the cloud scripts, but what exactly should I put in the LICENSE? Or would you rather I delete the entire cloud? (as well for me)

**Comment by TheCommCraft** [comment]
> I have already credited you in the cloud scripts, but what exactly should I put in the LICENSE? Or would you rather I delete the entire cloud? (as well for me)

That's ok

**Comment by RetrogradeDev** [comment]
Okay, the next time i work on the README.md, i'll credit you there to.
